# System parameters
dimensions: 'Two' # 'Two' or 'Three'
scenario: 'NY' # 'SYNTHETIC' or 'NY'
ue_pos: [ 100 , 105 ]  # TX UE position
B: 1 # number of BSs, up to 3 (including)
input_power: 20  # dBm
channel_bandwidth: 'NARROWBAND' # either 'NARROWBAND' or 'WIDEBAND'

# Bands parameters
K: [ 16 ] # number of subcarriers
Nr_x: [ 6 ] # number of RX n_elements in x. Also the number of elements used for the antenna in 2D.
Nr_y: [ 1 ] # number of RX n_elements in y.
fc: [ 6000 ]  # carr ier frequency in MHz
BW: [ 5 ] # BW frequency in MHz

# beamforming parameters
est_type: 'both' # 'angle','time','both'
aoa_res: 0.5  # resolution in degrees for the azimuth dictionary
zoa_res: 2  # resolution in degrees for the zenith dictionary
T_res: 0.005  # number of elements in the TIME dictionary in us
band_type: 'SINGLE' # 'SINGLE' or 'MULTI'

# general
seed: 0 # run seed
plot_estimation_results: True # either True or False