# general
seed: 0 # run seed
# System parameters
est_type: 'both' # 'angle','time','both'
dimensions: 'Two' # 'Two' or 'Three'
L: 4  # number of paths, up to 5 (including LOS)
B: 1 # number of BSs, up to 3 (including)
K: [ 48 ]   # number of subcarriers
Nr_x: [ 24 ] # number of RX n_elements in x. Also the number of elements used for the antenna in 2D.
Nr_y: [ 1 ] # number of RX n_elements in y.
aoa_res: 1.5  # resolution in degrees for the azimuth dictionary
zoa_res: 2  # resolution in degrees for the zenith dictionary
T_res: 0.002  # number of elements in the TIME dictionary
ue_pos: [ 9 , 4 ]  # TX UE position
sigma: 1  # noise standard deviation
fc: [ 24000 ]  # carrier frequency in MHz
BW: [ 400 ] # BW frequency in MHz
channel_bandwidth: 'NARROWBAND' # either 'NARROWBAND' or 'WIDEBAND'
plot_estimation_results: False # either True or False