# System parameters
scenario: 'NY' # 'SYNTHETIC' or 'NY'
ue_pos: [ 60 , 30 ]  # TX UE position
B: 1 # number of BSs, up to 3 (including)
input_power: 60  # dBm
channel_bandwidth: 'NARROWBAND' # either 'NARROWBAND' or 'WIDEBAND'

# Bands parameters
K: [ 40 ] # number of subcarriers
Nr: [ 12 ] # number of RX n_elements in x. Also the number of elements used for the antenna in 2D.
fc: [ 18000 ]  # carrier frequency in MHz
BW: [ 5 ] # BW frequency in MHz

# beamforming parameters
est_type: 'both' # 'angle','time','both'
aoa_res: 1  # resolution in degrees for the azimuth dictionary
T_res: 0.005  # number of elements in the TIME dictionary in us
band_type: 'SINGLE' # 'SINGLE' or 'MULTI'

# general
seed: 1 # run seed
plot_estimation_results: False # either True or False