# general
seed: 0 # run seed
# System parameters
L: 3  # number of paths (including LOS)
K: 20   # number of subcarriers
Nr: 32  # number of RX n_elements
Nb: 360  # number of elements in the ANGLE dictionary
T_res: 120  # number of elements in the TIME dictionary
Ns: 20  # number of transmitted pilot beams
ue_pos: [ 5, 0]  # RX (user) position, TX is assumed to be in [0, 0]
sigma: 0.1  # noise standard deviation
fc: 10000  # carrier frequency in MHz
BW: 50  # BW frequency in MHz
channel_bandwidth: 'NARROWBAND' # either 'NARROWBAND' or 'WIDEBAND'
plot_estimation_results: False