# System parameters
dimensions: 'Three' # 'Two' or 'Three'
ue_pos: [ 10 , 10 , 0 ]  # TX UE position
L: 1  # number of paths, up to 5 (including LOS)
B: 1 # number of BSs, up to 3 (including)
K: [ 12 ] # number of subcarriers
Nr_x: [ 7 ] # number of RX n_elements in x. Also the number of elements used for the antenna in 2D.
Nr_y: [ 7 ] # number of RX n_elements in y.
sigma: 1  # noise standard deviation
fc: [ 6000 ]  # carrier frequency in MHz
BW: [ 100 ] # BW frequency in MHz
channel_bandwidth: 'NARROWBAND' # either 'NARROWBAND' or 'WIDEBAND'

# beamforming parameters
est_type: 'both' # 'angle','time','both'
aoa_res: 1.5  # resolution in degrees for the azimuth dictionary
zoa_res: 2  # resolution in degrees for the zenith dictionary
T_res: 0.002  # number of elements in the TIME dictionary

# general
seed: 0 # run seed
plot_estimation_results: False # either True or False